---
title: "Difference mean distance all cities"
author: "Nicola Maiani"
date: '2023-08-04'
output: html_document
---

# Difference mean distance
## Preliminaries
```{r, message = FALSE, warning = FALSE}
test_pkg <- function(x)
  {
    if (!require(x, character.only = TRUE))
    {
      install.packages(x, dep = TRUE)
        if(!require(x, character.only = TRUE)) stop("Package not found")
    }
}

test_pkg("sf")
test_pkg("ggplot2")
test_pkg("sfnetworks")
test_pkg("tidyverse")
test_pkg("tidygraph")
test_pkg("dplyr")
test_pkg("tmap")
test_pkg("igraph")
test_pkg("units")
test_pkg("sp")
test_pkg("osmdata")
test_pkg("foreign")
test_pkg("raster")

dataFolder <- here::here("data")
RFolder <- here::here()
figureFolder <- here::here("figs")
```

```{r}
# # Load statpop data with BA values
statpop_be <- read.csv(file.path(dataFolder, "bern/statpop_be_BA_change.csv"), sep = ",", header = TRUE)
statpop_be <- statpop_be %>%
  mutate(city = "Bern")

statpop_ls <- read.csv(file.path(dataFolder, "lausanne/statpop_ls_BA_change.csv"), sep = ",", header = TRUE)
statpop_ls <- statpop_ls %>%
  mutate(city = "Lausanne")

statpop_wt <- read.csv(file.path(dataFolder, "winterthur/statpop_wt_BA_change.csv"), sep = ",", header = TRUE)
statpop_wt <- statpop_wt %>%
  mutate(city = "Winterthur")

statpop_zh <- read.csv(file.path(dataFolder, "zurich/statpop_zh_BA_change.csv"), sep = ",", header = TRUE)
statpop_zh <- statpop_zh %>%
  mutate(city = "Zurich")

statpop_all <- rbind(statpop_be, statpop_ls, statpop_wt, statpop_zh)

statpop_all <- statpop_zh

write_csv(statpop_all, file = file.path(dataFolder, "statpop_all_BA_change.csv"))
statpop_all <- read.csv(file.path(dataFolder, "statpop_all_BA_change.csv"), sep = ",", header = TRUE)
```

```{r}
# Calculate relative change of mdist
statpop_all <- statpop_all %>%
  mutate(rel_change_mdist = (mdist_tot_per - mdist_tot_real) / mdist_tot_real)

statpop_all <- statpop_all %>%
  mutate(rel_change_mdist = rel_change_mdist * 100)
summary(statpop_all$rel_change_mdist)

statpop_all <- statpop_all %>% mutate(rel_change_mdist = replace_na(rel_change_mdist, 0.0))
```

## Mean distances
```{r}
hist(statpop_all$mdist_tot_real, prob = T, xlab = "Mean distance", main = "Real mean distance")
summary(statpop_all$mdist_tot_real)
```

```{r}
hist(statpop_all$mdist_tot_per, prob = T, xlab = "Mean distance", main = "Perceived mean distance")
summary(statpop_all$mdist_tot_per)
```

## Change in mean distance
```{r}
# Using real mdist
hist(statpop_all$diff_mdist, prob = T, xlab = "Mean distance", main = "Change in mean distance")
summary(statpop_all$diff_mdist)
```

## Relative change in mean distance
```{r}
# Using real mdist
hist(statpop_all$rel_change_mdist, prob = T, xlab = "Relative change [%]", main = "Relative change of mean distance")
summary(statpop_all$rel_change_mdist)
```

## Compare values between cities
### Violin plots
```{r}
statpop_all$city <- as.factor(statpop_all$city)
```

```{r}
ggplot(statpop_all, aes(x=city, y=rel_change_mdist, color=city)) + geom_violin(trim = FALSE) +
  stat_summary(fun.y=median, geom="point", size=2, color="red") +
  stat_summary(fun.y=mean, geom="point", size=2, color="blue") +
  geom_boxplot(width=0.2, outlier.shape = NA) + theme_minimal() + ylab("Relative increase mean distance [%]") + xlab("City") +
  theme(legend.position = "none")
```

```{r}
ggplot(statpop_all, aes(x=city, y=diff_mdist, color=city)) + geom_violin(trim = FALSE) +
  stat_summary(fun.y=median, geom="point", size=2, color="red") +
  stat_summary(fun.y=mean, geom="point", size=2, color="blue") +
  geom_boxplot(width=0.2, outlier.shape = NA) + theme_minimal() + ylab("Absolute increase mean distance [m]") + xlab("City") +
  theme(legend.position = "none")
```

### Numerically
```{r}
statpop_all <- st_as_sf(x = statpop_all, coords = c("X", "Y"), crs = 2056)
```

### Lausanne
```{r}
# City borders
communities <- st_read(file.path(dataFolder, "gemeindegrenzen/swissBOUNDARIES3D_1_4_TLM_HOHEITSGEBIET.shp")) # load Swiss communities
border <- communities %>% filter(OBJEKTART == "Gemeindegebiet" & NAME == "Lausanne") %>% st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 2056)

# Take bounding box of community boundaries, since community consist of multiple parts
border <- st_as_sfc(st_bbox(border)) %>% st_as_sf()

statpop_ls <- st_filter(statpop_all, communities %>% filter(OBJEKTART == "Gemeindegebiet" & NAME == "Lausanne") %>% st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 2056))
summary(statpop_ls$rel_change_mdist)
summary(statpop_ls$diff_mdist)
summary(statpop_ls$diff_mdist_scaled)
```

### Zurich
```{r}
# City borders
communities <- st_read(file.path(dataFolder, "gemeindegrenzen/swissBOUNDARIES3D_1_4_TLM_HOHEITSGEBIET.shp")) # load Swiss communities
border <- communities %>% filter(OBJEKTART == "Gemeindegebiet" & NAME == "Zürich") %>% st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 2056)

statpop_zh <- st_filter(statpop_all, communities %>% filter(OBJEKTART == "Gemeindegebiet" & NAME == "Zürich") %>% st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 2056))
summary(statpop_zh$rel_change_mdist)
summary(statpop_zh$diff_mdist)
summary(statpop_zh$diff_mdist_scaled)
```

### Bern
```{r}
# City borders
communities <- st_read(file.path(dataFolder, "gemeindegrenzen/swissBOUNDARIES3D_1_4_TLM_HOHEITSGEBIET.shp")) # load Swiss communities
border <- communities %>% filter(OBJEKTART == "Gemeindegebiet" & NAME == "Bern") %>% st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 2056)

statpop_be <- st_filter(statpop_all, communities %>% filter(OBJEKTART == "Gemeindegebiet" & NAME == "Bern") %>% st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 2056))
summary(statpop_be$rel_change_mdist)
summary(statpop_be$diff_mdist)
summary(statpop_be$diff_mdist_scaled)
```

### Winterthur
```{r}
# City borders
communities <- st_read(file.path(dataFolder, "gemeindegrenzen/swissBOUNDARIES3D_1_4_TLM_HOHEITSGEBIET.shp")) # load Swiss communities
border <- communities %>% filter(OBJEKTART == "Gemeindegebiet" & NAME == "Winterthur") %>% st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 2056)

statpop_wt <- st_filter(statpop_all, communities %>% filter(OBJEKTART == "Gemeindegebiet" & NAME == "Winterthur") %>% st_zm(drop = TRUE, what = "ZM") %>% st_transform(crs = 2056))
summary(statpop_wt$rel_change_mdist)
summary(statpop_wt$diff_mdist)
summary(statpop_wt$diff_mdist_scaled)
```





